services:
  app:
    build: .
    container_name: wayni-movil-app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - wayni_network

  mongo:
    image: mongo:latest
    container_name: wayni-movil-mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - wayni_network

networks:
  wayni_network:
    driver: bridge

volumes:
  mongo_data:
