name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install Node Version Manager (NVM)
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        source ~/.nvm/nvm.sh

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@195.35.18.33 "
          cd /var/www/Clients/Wayni &&
          git fetch &&
          git pull &&
          source ~/.nvm/nvm.sh &&
          nvm install 20 &&
          nvm use 20 &&
          npm install &&
          npm run build
        "